BartendingRefresher/urls.py
from django.conf.urls import url
from . import views

app_name = 'BG'
urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name = 'index'),
    url(r'submit/', views.SubmitView.as_view(), name = 'submit'),
    url(r'^(?P<Model>\w+)/$', views.DrinkView, name = 'ListOfDrinks'),
    url(r'^(?P<Model>[\w\s]+)/(?P<Drink>[\w\s]+)$', views.DetailView.as_view(), name = 'Detail'),
    url(r'^about$', views.AboutView, name = 'About'),
]

TestSite/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url('polls/', include('polls.urls')),
    url('bargame/', include('BartendingRefresher.urls'))
]

polls/urls.py
from django.conf.urls import url
from . import views

app_name = 'polls'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^random_number/$', views.random_generator, {'max_rand':100}, name='number generator default'),
    url(r'^random_number/(?P<max_rand>\d+)/$', views.random_generator, name='number generator max given'),
    url(r'^(?P<question_id>\d+)/$', views.detail, name = 'detail'),
    url(r'^(?P<question_id>\d+)/results/$', views.results, name='results'),
    url(r'^(?P<question_id>\d+)/vote/$', views.vote, name='vote'),

]

BartendingRefresher/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
from django.db.models import Q

# Create your models here.
class Ingredient(models.Model):
	# TODO-Suggestion: Captial case the Ingredient field
	Ingredient = models.CharField(max_length=20, primary_key=True)
	Type = models.CharField(max_length=10,
							choices=[
								('Al', 'Alcohol'),
								('Li', 'Liqueur'),
								('Gr', 'Garnish'),
								('Fill', 'Filler')
							],
							blank=False,
							)

	@classmethod
	def IngredientList(cls, *args):
		# TODO-Fix: Return PK, this will throw queryset error
		#Dynamically returns query set. Uses reduce to build a query string. ie Q(Type='Al')|Q(Type='Li')|Q(Type=etc...)
		return {'pk__in':Ingredient.objects.filter(reduce(lambda x, y: x|y, [Q(Type=type) for type in args]))}

	def __repr__(self):
		return '%s, %s' %(self.Ingredient, self.Type)

	def __str__(self):
		return self.Ingredient

class Drink(models.Model):
	name = models.CharField(max_length=30, primary_key=True, blank=False,)
	glass = models.CharField(max_length=20, blank=False,)
	method = models.CharField(max_length=10, blank=False)
	alcohol = models.CharField(max_length=10, blank=False)

	class Meta:
		abstract = True

	def get_fields_and_values(self):
		return [(field.name.capitalize(), field.value_to_string(self)) for field in self.__class__._meta.fields]
#
# class Martini(Drink):
#     pass

class Russian(Drink):
	#TODO-Suggestion Capital case the fields below
	method = models.CharField(max_length=10, default='Build',)
	glass = models.CharField(max_length=20, default='Rocks',)
	alcohol = models.ForeignKey(Ingredient, related_name='%(class)s_Alcohol', \
								on_delete=models.CASCADE, default='Vodka',
								limit_choices_to=Ingredient.IngredientList('Al', 'Li'),
								blank=False,
								)
	second_alcohol = models.ForeignKey(Ingredient, related_name='%(class)s_Second', \
										on_delete=models.CASCADE,
										limit_choices_to=Ingredient.IngredientList('Al', 'Li'),
									   	blank=False,
										)
	third_alcohol = models.ForeignKey(Ingredient, related_name='%(class)s_Third', \
										on_delete=models.CASCADE, blank=True, null=True, \
										limit_choices_to=Ingredient.IngredientList('Al', 'Li'),
										)
	garnish = models.ForeignKey(Ingredient, related_name='%(class)s_Garnish', \
								on_delete=models.CASCADE, blank=True, null=True, \
								limit_choices_to=Ingredient.IngredientList('Gr'),
								)
	filler = models.ForeignKey(Ingredient, related_name='%(class)s_Filler', \
								on_delete=models.CASCADE, blank=True, null=True,
								limit_choices_to=Ingredient.IngredientList('Fill'),
								)

	def __init__(self, *args, **kwargs):
		super(Russian, self).__init__(*args, **kwargs)



	def __repr__(self):
		return '%s, %s, %s, %s, %s, %s' %(self.name, self.method, self.glass, \
											self.alcohol, self.second_alcohol, self.garnish)

	def __str__(self):
		return self.name

# class God(Drink):
#     glass = 'Rocks'
#     type = 'Build'
#     garnish = 'None'


# class Screws(Drink):
#     pass
#
# class FizzSours(Drink):#     pass


class Bartender():
	menu = {'Russian': Russian}

	def MakeDrink(self, type, **kwargs):

		return self.menu[type.capitalize()](**kwargs)

BartendingRefresher/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render
from django.http.response import HttpResponse
from django.views import generic
from django.apps import apps
from .models import Drink, Russian, Ingredient, Bartender

# Create your views here.

class IndexView(generic.ListView):

    #TODO-Fix: Drink model no longer used; Drink has no objects attribute
    def get(self, request):
        # VodkaDrinks = Ingredient.objects.get(Ingredient='Vodka')
        #
        # return VodkaDrinks.russian_Alcohol.all()
        Drink_Types = []
        for model in apps.get_app_config('BartendingRefresher').get_models():
            if issubclass(model, Drink) and model is not Drink:
                Drink_Types.append(model.__name__)

        #TODO-Fix: Make it return all objects of the model or just the model name
        return render(request, 'BartendingRefresher/index.html', {'DrinkTypes':Drink_Types})

# def IndexView(request):
#     model_list = []
#     for model in apps.get_app_config('BartendingRefresher').get_models():
#         if issubclass(model, Drink) and model is not Drink:
#             model_list[model.__name__] = model
#
#     return HttpResponse(model_list)

# class DetailView(generic.ListView):
#
#     def get(self, request, Model):
#         model = Bartender(Model)
#         return HttpResponse(model.objects.all())

def DrinkView(request, Model):
	bartender = Bartender()
	model = bartender.MakeDrink(Model)
	context = {
		'ListOfDrinks': model.__class__.objects.all(),
		'Model': Model
		}
	return render(request, 'BartendingRefresher/ListOfDrinks.html', context)

class DetailView(generic.ListView):
	#passed Model and Drink name. Need to call Factory method Bartender to return Model and then
	#Query to get ingredients list with pk="drink name"
	#return the list of ingredients to detail page.

	#How to get passed parameter...model... and drink name...?
	template_name = 'BartendingRefresher/detail.html'
	context_object_name = 'Drink'

	def get_queryset(self):
		context=super(DetailView, self)
		bartender = Bartender()

		#Accessing parameters via self.kwargs['parameter variable']
		model = bartender.MakeDrink(self.kwargs['Model'])

		return model.__class__.objects.get(name=self.kwargs['Drink'])


# def DetailView(request, Drink):
# 	context = {'test':Drink}
#
# 	return render(request, 'BartendingRefresher /detail.html', context)
#
#

def AboutView(request):
	return render(request, 'BartendingRefresher/about.html')

class SubmitView(generic.DetailView):
    pass

BartendingRefresher/templates/BartendingRefresher/ListOfDrinks.html
{% extends 'BartendingRefresher/basetemplate.html' %}

{% block body %}
    {%if ListOfDrinks%}
        {%for Drink in ListOfDrinks%}
            <li><a href="{% url 'BG:Detail' Model Drink.name %}">{{ Drink }}</a></li>
        {%endfor%}
    {%else%}
        <p>No drinks for this category yet.</p>
    {%endif%}
{% endblock %}

BartendingRefresher/templates/BartendingRefresher/about.html
{% extends 'BartendingRefresher/basetemplate.html' %}

{%block body%}
<h1>About Page</h1>
<p>Hello, this is website is my way of learning how to improve myself and trying to step into the shoes of a
web-developer using the django11.1 framework and python2.7. <br><br>

Eventually, the plan will be to incorporate additional things as I learn and progress. Currently on the list is
<b>React</b> for a better user experience.</p>
{%endblock%}

BartendingRefresher/templates/BartendingRefresher/basetemplate.html
<!DOCTYPE html>
<html lang="en">
<head>

    <meta charset="UTF-8">
    <meta name = "viewpoint" content="width=device-width, initial-scale=1">
    <title>Bartending Refresher</title>
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">

</head>

<body>
    <nav class="navbar navbar-inverse">
        <div class="container-fluid">

            <div class="navbar-header">
                <a href="{% url 'BG:index' %}" class="navbar-brand">BarRefresher</a>
            </div>

            <div>
                <ul class="nav navbar-nav">
                    <li><a href="{% url 'BG:index' %}">Home</a></li>
                    <li><a href="{% url 'BG:About' %}">About</a></li>
                    <li><a href="#">Contact</a></li>
                </ul>
            </div>

        </div>
    </nav>

    {% block body %}
    {% endblock %}

</body>
</html>

BartendingRefresher/templates/BartendingRefresher/detail.html
{% extends 'BartendingRefresher/basetemplate.html' %}

{% block body %}
    {% if Drink %}
    <!--TODO-Suggestion: display the list of ingredients for the drink-->

    <!--{{Drink.get_fields_and_values}}-->
        {% for Field, Value in Drink.get_fields_and_values %}
            {% if Value != 'None' %}
                <li>{{Field}} --- {{Value}}</li>
            {% endif %}
                <!--{% for Field, Ingredient in Ingredients.items %}-->
                    <!--<li>{{Field}}:  {{Ingredient}}</li>-->
                <!--{% endfor %}-->
        {%endfor%}

    {% else %}

        <p>No Ingredients Yet.</p>

    {% endif %}
{% endblock %}

BartendingRefresher/templates/BartendingRefresher/index.html
{% extends 'BartendingRefresher/basetemplate.html' %}

{% block body %}
    {% if DrinkTypes %}
        {% for Type in DrinkTypes %}

            <li><a href='{% url "BG:ListOfDrinks" Type %}'>{{ Type }}</a></li>

        {% endfor %}
    {% else %}
        <p>Bar is closed.</p>

    {% endif %}
{% endblock %}